### ISSUE TITLE
Disable auto focus when editor is loaded. 

### ISSUE THREAD

**Issue by billyranario** [flyween/vue3-quill#4]
Is there any way to disable autofocos on editor when data is loaded? I got this problem in an Edit page of my application. Thanks

**Comment by flyween** [comment]
`Vue3-quill` will call API `pasteHTML` or API `setText` when you change the content.This situation may be caused by the API.
You can set props `disabled` 's value to `false` before change the content.And set value to `true` after content's value changed.
`Vue3-quill`'s event `change` will tell you that changed action has done.

**Comment by flyween** [comment]
And if you find some other way to resolve this,welcome PR.
